import enum


class WorkflowStatus(str, enum.Enum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    SUCCESS = "SUCCESS"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class TaskStatus(str, enum.Enum):
    PENDING = "PENDING"
    READY = "READY"
    RUNNING = "RUNNING"
    SUCCESS = "SUCCESS"
    FAILED = "FAILED"
    RETRYING = "RETRYING"
    TIMED_OUT = "TIMED_OUT"
    DEAD_LETTERED = "DEAD_LETTERED"


class TaskType(str, enum.Enum):
    HTTP = "HTTP"
    PYTHON_FUNCTION = "PYTHON_FUNCTION"
    DATABASE = "DATABASE"
    DELAY = "DELAY"


class BackoffStrategy(str, enum.Enum):
    FIXED = "fixed"
    LINEAR = "linear"
    EXPONENTIAL = "exponential"


class WorkerStatus(str, enum.Enum):
    ACTIVE = "ACTIVE"
    PAUSED = "PAUSED"
    DEAD = "DEAD"


class EventType(str, enum.Enum):
    WORKFLOW_CREATED = "WORKFLOW_CREATED"
    WORKFLOW_STARTED = "WORKFLOW_STARTED"
    WORKFLOW_COMPLETED = "WORKFLOW_COMPLETED"
    WORKFLOW_FAILED = "WORKFLOW_FAILED"
    WORKFLOW_CANCELLED = "WORKFLOW_CANCELLED"

    TASK_SCHEDULED = "TASK_SCHEDULED"
    TASK_CLAIMED = "TASK_CLAIMED"
    TASK_HEARTBEAT = "TASK_HEARTBEAT"
    TASK_LEASE_EXPIRED = "TASK_LEASE_EXPIRED"
    TASK_STARTED = "TASK_STARTED"
    TASK_COMPLETED = "TASK_COMPLETED"
    TASK_FAILED = "TASK_FAILED"
    TASK_RETRY_SCHEDULED = "TASK_RETRY_SCHEDULED"
    TASK_DEAD_LETTERED = "TASK_DEAD_LETTERED"

    WORKER_REGISTERED = "WORKER_REGISTERED"
    WORKER_DEREGISTERED = "WORKER_DEREGISTERED"
    WORKER_HEARTBEAT_TIMEOUT = "WORKER_HEARTBEAT_TIMEOUT"
